sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: false
  tier: db-f1-micro
ingress:
  url: https://tiltakspenger-meldekort-api.intern.dev.nav.no
cluster: dev-gcp
replicas: 1
kafka-pool: "nav-dev"
outboundExternalUrls:
  dokarkiv: dokarkiv-q2.dev-fss-pub.nais.io
