sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: false
  tier: db-f1-micro
ingress:
  url: https://tiltakspenger-meldekort-api.intern.dev.nav.no
replicas:
  min: 1
  max: 2
kafka-pool: "nav-dev"
outboundExternalUrls:
  dokarkiv: dokarkiv-q2.dev-fss-pub.nais.io
  arenaMeldekortService: meldekortservice-q2.dev-fss-pub.nais.io
arenaMeldekortServiceApp: meldekortservice-q2
arenaMeldekortFrontend:
  envs:
    - app: meldekort-frontend-q1
    - app: meldekort-frontend-q2
naisEnv: dev
