apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-meldekort-api
  namespace: tpts
  labels:
    team: tpts
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{ image }}
  port: 8080
  replicas:
  {{#with replicas}}
    min: {{ replicas.min }}
    max: {{ replicas.max }}
  {{/#with}}
  ingresses:
    - {{ ingress.url }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: {{ kafka-pool }}
  leaderElection: true
  gcp:
    sqlInstances:
      - name: tiltakspenger-meldekort-api
        type: POSTGRES_17
        tier: {{ sqlInstances.tier }}
        diskAutoresize: {{ sqlInstances.diskAutoresize }}
        pointInTimeRecovery: {{ sqlInstances.pointInTimeRecovery }}
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: meldekort
            envVarPrefix: DB
  accessPolicy:
    outbound:
      rules:
        - application: tiltakspenger-saksbehandling-api
        - application: tiltakspenger-pdfgen
      external:
        - host: {{outboundExternalUrls.dokarkiv}}
    inbound:
      rules:
        - application: tiltakspenger-meldekort
        - application: tiltakspenger-saksbehandling-api
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
